DROP DATABASE IF EXISTS easy_serve_db;
CREATE DATABASE easy_serve_db;
USE easy_serve_db;

CREATE TABLE hotDogs (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  food VARCHAR(45) NOT NULL,  
);


CREATE TABLE drinks (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  drink VARCHAR(45) NOT NULL,  
  
);

CREATE TABLE IceCreams (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  IceCream VARCHAR(45) NOT NULL,  
  
);